export default [
  {
    "login": "kvnol",
    "id": 3299130,
    "node_id": "MDQ6VXNlcjMyOTkxMzA=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3299130?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kvnol",
    "html_url": "https://github.com/kvnol",
    "followers_url": "https://api.github.com/users/kvnol/followers",
    "following_url": "https://api.github.com/users/kvnol/following{/other_user}",
    "gists_url": "https://api.github.com/users/kvnol/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kvnol/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kvnol/subscriptions",
    "organizations_url": "https://api.github.com/users/kvnol/orgs",
    "repos_url": "https://api.github.com/users/kvnol/repos",
    "events_url": "https://api.github.com/users/kvnol/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kvnol/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "sanderdms",
    "id": 13978390,
    "node_id": "MDQ6VXNlcjEzOTc4Mzkw",
    "avatar_url": "https://avatars.githubusercontent.com/u/13978390?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sanderdms",
    "html_url": "https://github.com/sanderdms",
    "followers_url": "https://api.github.com/users/sanderdms/followers",
    "following_url": "https://api.github.com/users/sanderdms/following{/other_user}",
    "gists_url": "https://api.github.com/users/sanderdms/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sanderdms/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sanderdms/subscriptions",
    "organizations_url": "https://api.github.com/users/sanderdms/orgs",
    "repos_url": "https://api.github.com/users/sanderdms/repos",
    "events_url": "https://api.github.com/users/sanderdms/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sanderdms/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "KasraTabrizi",
    "id": 36457522,
    "node_id": "MDQ6VXNlcjM2NDU3NTIy",
    "avatar_url": "https://avatars.githubusercontent.com/u/36457522?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/KasraTabrizi",
    "html_url": "https://github.com/KasraTabrizi",
    "followers_url": "https://api.github.com/users/KasraTabrizi/followers",
    "following_url": "https://api.github.com/users/KasraTabrizi/following{/other_user}",
    "gists_url": "https://api.github.com/users/KasraTabrizi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/KasraTabrizi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/KasraTabrizi/subscriptions",
    "organizations_url": "https://api.github.com/users/KasraTabrizi/orgs",
    "repos_url": "https://api.github.com/users/KasraTabrizi/repos",
    "events_url": "https://api.github.com/users/KasraTabrizi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/KasraTabrizi/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "AlineLanckneus",
    "id": 49918534,
    "node_id": "MDQ6VXNlcjQ5OTE4NTM0",
    "avatar_url": "https://avatars.githubusercontent.com/u/49918534?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/AlineLanckneus",
    "html_url": "https://github.com/AlineLanckneus",
    "followers_url": "https://api.github.com/users/AlineLanckneus/followers",
    "following_url": "https://api.github.com/users/AlineLanckneus/following{/other_user}",
    "gists_url": "https://api.github.com/users/AlineLanckneus/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/AlineLanckneus/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/AlineLanckneus/subscriptions",
    "organizations_url": "https://api.github.com/users/AlineLanckneus/orgs",
    "repos_url": "https://api.github.com/users/AlineLanckneus/repos",
    "events_url": "https://api.github.com/users/AlineLanckneus/events{/privacy}",
    "received_events_url": "https://api.github.com/users/AlineLanckneus/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jseeuws",
    "id": 56020996,
    "node_id": "MDQ6VXNlcjU2MDIwOTk2",
    "avatar_url": "https://avatars.githubusercontent.com/u/56020996?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jseeuws",
    "html_url": "https://github.com/jseeuws",
    "followers_url": "https://api.github.com/users/jseeuws/followers",
    "following_url": "https://api.github.com/users/jseeuws/following{/other_user}",
    "gists_url": "https://api.github.com/users/jseeuws/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jseeuws/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jseeuws/subscriptions",
    "organizations_url": "https://api.github.com/users/jseeuws/orgs",
    "repos_url": "https://api.github.com/users/jseeuws/repos",
    "events_url": "https://api.github.com/users/jseeuws/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jseeuws/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Calliyope",
    "id": 56021092,
    "node_id": "MDQ6VXNlcjU2MDIxMDky",
    "avatar_url": "https://avatars.githubusercontent.com/u/56021092?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Calliyope",
    "html_url": "https://github.com/Calliyope",
    "followers_url": "https://api.github.com/users/Calliyope/followers",
    "following_url": "https://api.github.com/users/Calliyope/following{/other_user}",
    "gists_url": "https://api.github.com/users/Calliyope/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Calliyope/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Calliyope/subscriptions",
    "organizations_url": "https://api.github.com/users/Calliyope/orgs",
    "repos_url": "https://api.github.com/users/Calliyope/repos",
    "events_url": "https://api.github.com/users/Calliyope/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Calliyope/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "NaoyukiArakawa",
    "id": 56021399,
    "node_id": "MDQ6VXNlcjU2MDIxMzk5",
    "avatar_url": "https://avatars.githubusercontent.com/u/56021399?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/NaoyukiArakawa",
    "html_url": "https://github.com/NaoyukiArakawa",
    "followers_url": "https://api.github.com/users/NaoyukiArakawa/followers",
    "following_url": "https://api.github.com/users/NaoyukiArakawa/following{/other_user}",
    "gists_url": "https://api.github.com/users/NaoyukiArakawa/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/NaoyukiArakawa/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/NaoyukiArakawa/subscriptions",
    "organizations_url": "https://api.github.com/users/NaoyukiArakawa/orgs",
    "repos_url": "https://api.github.com/users/NaoyukiArakawa/repos",
    "events_url": "https://api.github.com/users/NaoyukiArakawa/events{/privacy}",
    "received_events_url": "https://api.github.com/users/NaoyukiArakawa/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "ricojr",
    "id": 56021402,
    "node_id": "MDQ6VXNlcjU2MDIxNDAy",
    "avatar_url": "https://avatars.githubusercontent.com/u/56021402?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ricojr",
    "html_url": "https://github.com/ricojr",
    "followers_url": "https://api.github.com/users/ricojr/followers",
    "following_url": "https://api.github.com/users/ricojr/following{/other_user}",
    "gists_url": "https://api.github.com/users/ricojr/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ricojr/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ricojr/subscriptions",
    "organizations_url": "https://api.github.com/users/ricojr/orgs",
    "repos_url": "https://api.github.com/users/ricojr/repos",
    "events_url": "https://api.github.com/users/ricojr/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ricojr/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "digitalnomad81",
    "id": 56021415,
    "node_id": "MDQ6VXNlcjU2MDIxNDE1",
    "avatar_url": "https://avatars.githubusercontent.com/u/56021415?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/digitalnomad81",
    "html_url": "https://github.com/digitalnomad81",
    "followers_url": "https://api.github.com/users/digitalnomad81/followers",
    "following_url": "https://api.github.com/users/digitalnomad81/following{/other_user}",
    "gists_url": "https://api.github.com/users/digitalnomad81/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/digitalnomad81/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/digitalnomad81/subscriptions",
    "organizations_url": "https://api.github.com/users/digitalnomad81/orgs",
    "repos_url": "https://api.github.com/users/digitalnomad81/repos",
    "events_url": "https://api.github.com/users/digitalnomad81/events{/privacy}",
    "received_events_url": "https://api.github.com/users/digitalnomad81/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "CathDM",
    "id": 56021485,
    "node_id": "MDQ6VXNlcjU2MDIxNDg1",
    "avatar_url": "https://avatars.githubusercontent.com/u/56021485?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/CathDM",
    "html_url": "https://github.com/CathDM",
    "followers_url": "https://api.github.com/users/CathDM/followers",
    "following_url": "https://api.github.com/users/CathDM/following{/other_user}",
    "gists_url": "https://api.github.com/users/CathDM/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/CathDM/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/CathDM/subscriptions",
    "organizations_url": "https://api.github.com/users/CathDM/orgs",
    "repos_url": "https://api.github.com/users/CathDM/repos",
    "events_url": "https://api.github.com/users/CathDM/events{/privacy}",
    "received_events_url": "https://api.github.com/users/CathDM/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Steven-Nuyttens",
    "id": 56021509,
    "node_id": "MDQ6VXNlcjU2MDIxNTA5",
    "avatar_url": "https://avatars.githubusercontent.com/u/56021509?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Steven-Nuyttens",
    "html_url": "https://github.com/Steven-Nuyttens",
    "followers_url": "https://api.github.com/users/Steven-Nuyttens/followers",
    "following_url": "https://api.github.com/users/Steven-Nuyttens/following{/other_user}",
    "gists_url": "https://api.github.com/users/Steven-Nuyttens/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Steven-Nuyttens/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Steven-Nuyttens/subscriptions",
    "organizations_url": "https://api.github.com/users/Steven-Nuyttens/orgs",
    "repos_url": "https://api.github.com/users/Steven-Nuyttens/repos",
    "events_url": "https://api.github.com/users/Steven-Nuyttens/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Steven-Nuyttens/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "stijn-peeters",
    "id": 56021635,
    "node_id": "MDQ6VXNlcjU2MDIxNjM1",
    "avatar_url": "https://avatars.githubusercontent.com/u/56021635?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/stijn-peeters",
    "html_url": "https://github.com/stijn-peeters",
    "followers_url": "https://api.github.com/users/stijn-peeters/followers",
    "following_url": "https://api.github.com/users/stijn-peeters/following{/other_user}",
    "gists_url": "https://api.github.com/users/stijn-peeters/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/stijn-peeters/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/stijn-peeters/subscriptions",
    "organizations_url": "https://api.github.com/users/stijn-peeters/orgs",
    "repos_url": "https://api.github.com/users/stijn-peeters/repos",
    "events_url": "https://api.github.com/users/stijn-peeters/events{/privacy}",
    "received_events_url": "https://api.github.com/users/stijn-peeters/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "pawansgithub",
    "id": 68653836,
    "node_id": "MDQ6VXNlcjY4NjUzODM2",
    "avatar_url": "https://avatars.githubusercontent.com/u/68653836?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/pawansgithub",
    "html_url": "https://github.com/pawansgithub",
    "followers_url": "https://api.github.com/users/pawansgithub/followers",
    "following_url": "https://api.github.com/users/pawansgithub/following{/other_user}",
    "gists_url": "https://api.github.com/users/pawansgithub/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/pawansgithub/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/pawansgithub/subscriptions",
    "organizations_url": "https://api.github.com/users/pawansgithub/orgs",
    "repos_url": "https://api.github.com/users/pawansgithub/repos",
    "events_url": "https://api.github.com/users/pawansgithub/events{/privacy}",
    "received_events_url": "https://api.github.com/users/pawansgithub/received_events",
    "type": "User",
    "site_admin": false
  }
];
