export default {
  "login": "crissesoto",
  "id": 46997688,
  "node_id": "MDQ6VXNlcjQ2OTk3Njg4",
  "avatar_url": "https://avatars.githubusercontent.com/u/46997688?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/crissesoto",
  "html_url": "https://github.com/crissesoto",
  "followers_url": "https://api.github.com/users/crissesoto/followers",
  "following_url": "https://api.github.com/users/crissesoto/following{/other_user}",
  "gists_url": "https://api.github.com/users/crissesoto/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/crissesoto/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/crissesoto/subscriptions",
  "organizations_url": "https://api.github.com/users/crissesoto/orgs",
  "repos_url": "https://api.github.com/users/crissesoto/repos",
  "events_url": "https://api.github.com/users/crissesoto/events{/privacy}",
  "received_events_url": "https://api.github.com/users/crissesoto/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Crisse Soto",
  "company": null,
  "blog": "",
  "location": "Ghent",
  "email": null,
  "hireable": null,
  "bio": "Fullstack Web developer",
  "twitter_username": null,
  "public_repos": 75,
  "public_gists": 2,
  "followers": 13,
  "following": 11,
  "created_at": "2019-01-24T12:17:38Z",
  "updated_at": "2021-09-08T12:21:39Z"
};
